---
name: example
description: example of pedantic_sensuikan1973.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  meta: ^1.11.0
  pedantic_sensuikan1973:
    path: ..
