---
name: example
description: example of pedantic_sensuikan1973.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.18.6 <4.0.0'
dependencies:
  meta: ^1.9.1
  pedantic_sensuikan1973:
    path: ..
