---
name: pedantic_sensuikan1973
version: 4.0.1
description: The best Dart analyzer settings are used. sensuikan1973 edition.
homepage: https://github.com/sensuikan1973/pedantic_sensuikan1973

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter_lints: ^2.0.1
