name: pedantic_sensuikan1973
version: 3.0.0
description: The best Dart analyzer settings are used. sensuikan1973 edition.
homepage: https://github.com/sensuikan1973/pedantic_sensuikan1973

environment:
  sdk: '>=2.15.0-0 <3.0.0'
