name: pedantic_sensuikan1973
version: 1.5.0
description: This package supplies strict analysis options
homepage: https://github.com/sensuikan1973/pedantic_sensuikan1973

environment:
  sdk: '>=2.8.0 <3.0.0'
