---
name: Create Release

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  create_release:
    # See: .github/workflows/create_release_pr.yaml
    if: ${{ github.head_ref == 'prepare_for_release' && github.event.pull_request.merged == true }}
    env:
      RELEASE_DESCRIPTION_TXT_FILE: release_description.txt
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: dart-lang/setup-dart@v1

      - name: inject current version
        shell: bash # for windows
        run: echo "CURRENT_VERSION=$(dart pub global run cider version)" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ env.CURRENT_VERSION }}
          files: ${{ env.PUBLISH_DIR }}/${{ runner.os }}.zip
          generate_release_notes: true
