---
name: Dart CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dart_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: dart format
        run: dart format ./ -l 120 --set-exit-if-changed

  dart_analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: install dependencies
        run: dart pub get
      - name: analyzer
        run: dart analyze --fatal-infos --fatal-warnings .

  dart_run_example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart example/main.dart
